# Generated by Django 4.1.3 on 2022-11-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Tipo", models.IntegerField()),
                ("Data", models.DateField()),
                ("Valor", models.IntegerField()),
                ("CPF", models.CharField(max_length=50)),
                ("Cartão", models.CharField(max_length=12)),
                ("Hora", models.TimeField()),
                ("DonoDaLoja", models.CharField(max_length=50)),
                ("NomeLoja", models.CharField(max_length=50)),
            ],
        ),
    ]
